ALTER TABLE friends DROP CONSTRAINT FK_39;
ALTER TABLE friends DROP CONSTRAINT FK_42;
DROP TABLE friends;

ALTER TABLE posts DROP CONSTRAINT FK_45;
DROP TABLE posts;

ALTER TABLE messages DROP CONSTRAINT FK_33;
ALTER TABLE messages DROP CONSTRAINT FK_36;
ALTER TABLE messages DROP CONSTRAINT PK_messages;
DROP TABLE messages;

ALTER TABLE users DROP CONSTRAINT PK_users;
DROP TABLE users;
